[project]
name = "game_of_life_YetiYetYet"
version = "0.1.0"
authors = [
  { name="Alexis BEHIER", email="alexisbehier22@gmail.com" },
]
description = "This package is a Python implementation of Conway's Game of Life,a cellular automaton devised by the British mathematician John Horton Conway in 1970. The game is a zero-player game, meaning that its evolution is determined by its initial state, requiring no further input. One interacts with the Game of Life by creating an initial configuration and observing how it evolves."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/YetiYetYet/game-of-life-python"
"Bug Tracker" = "https://github.com/YetiYetYet/game-of-life-python/issues"