[build-system]
requires = [ "setuptools", "setuptools-scm", "wheel", "twine" ]
build-backend = "setuptools.build_meta"

[project]
name = "fdfdtest"
version = "1.7"
description = "Yantu tools for python"
requires-python = ">=3.8"
keywords= ["python", "yantu", "中文"]
dependencies = []
authors = [
    { name="GuoHuai Wu", email="wu466687121@qq.com" },
  ]
license = {text = "MIT License"}