[project]
name = "rdpywheel"
version = "0.1.14"
description = "reddwarf public python lib"
authors = [
    {name = "jiang qiang", email = "jiangtingqiang@gmail.com"},
]
dependencies = [
    "setuptools~=68.1.2",
    "requests~=2.28.2",
    "python-dotenv==1.0.0",
    "jwt>=1.3.1",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

