[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "djseong-test-bar-2"
authors = [
    {name = "djseong", email = "feedback@gmail.com"},
]
description = "test bar"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
]
version = "0.1.0"
dependencies = []