[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "plotterclassprogra"
version = "0.0.4"
authors = [
    { name="Manex Bengoa"},
    { name="Cristian Pazos"},
]
description = "Clase dedicada a poder visualizar diferentes tipos de graficos tras un clustering"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/cristianpazos9/proyecto_programacion"
"Bug Tracker" = "https://github.com/cristianpazos9/proyecto_programacion/issues"