- name: "deployment #1"
  project_guid: "90d902e6-401f-4d07-bae1-c85b4e4a547d"
  app_name: "Service #1"
  owner_name: "My name"
  environment_name: "NonProd-Dev#1"
  requester_name: "My name"
  guid: "47754e1e-57a9-4072-94b8-0f62514df847"
  last_seen: "2023-10-15 10:34:00"
  success: true
  finished: true
  item_created_at: "2023-10-01 10:34:00"
  item_updated_at: "2023-10-05 20:34:00"
  active: true
- name: "deployment #2"
  project_guid: "90d902e6-401f-4d07-bae1-c85b4e4a547d"
  app_name: "Service #2"
  owner_name: "third one"
  environment_name: "NonProd-Construction"
  requester_name: "My name"
  guid: "0fc072a2-7f8d-4430-8b06-54956c904a35"
  last_seen: "2023-10-15 10:34:00"
  success: true
  finished: true
  item_created_at: "2022-10-01 10:34:00"
  item_updated_at: "2022-10-05 20:34:00"
  active: true
- name: "deployment #3"
  project_guid: "def9d06f-6e6c-4191-b182-a4ee8e188731"
  app_name: "Service #3"
  owner_name: "other one"
  environment_name: "prod-prod"
  requester_name: "other one"
  guid: "50f4eaf8-8096-440a-a47e-aa47ecd5e7c7"
  last_seen: "2023-10-15 10:34:00"
  success: true
  finished: true
  item_created_at: "2023-05-01 10:34:00"
  item_updated_at: "2023-05-05 20:34:00"
  active: true
- name: "deployment #4"
  project_guid: "def9d06f-6e6c-4191-b182-a4ee8e188731"
  app_name: "Service #4"
  owner_name: "other one"
  environment_name: "prod-prod"
  requester_name: "other one"
  guid: "84a8813a-b5fb-4278-9701-eea19f201dc9"
  last_seen: "2023-10-15 10:34:00"
  success: true
  finished: true
  item_created_at: "2023-09-01 8:34:00"
  item_updated_at: "2023-09-05 14:34:00"
  active: true
- name: "deployment #5"
  project_guid: "33ce3ece-433d-47e5-b6de-010174ae0990"
  app_name: "Service #5"
  owner_name: "other one"
  environment_name: "prod-prod"
  requester_name: "other one"
  guid: "eaaa9b02-c2b1-411c-a98f-2faeaf549d34"
  last_seen: "2023-10-15 10:34:00"
  success: true
  finished: true
  item_created_at: "2023-07-01 10:34:00"
  item_updated_at: "2023-07-09 20:34:00"
  active: true
- name: "deployment #6"
  project_guid: "33ce3ece-433d-47e5-b6de-010174ae0990"
  app_name: "Service #6"
  owner_name: "last_customer"
  environment_name: "prod-prod"
  requester_name: "last_customere"
  guid: "bce12fa5-60e9-4fbf-8edb-edddb87c0d2b"
  last_seen: "2023-10-15 10:34:00"
  success: true
  finished: true
  item_created_at: "2023-05-08 11:34:00"
  item_updated_at: "2023-05-09 20:34:00"
  active: true
- name: "deployment #7"
  project_guid: "33ce3ece-433d-47e5-b6de-010174ae0990"
  app_name: "Service #6"
  owner_name: "last_customer"
  environment_name: "prod-prod"
  requester_name: "last_customere"
  guid: "ace19fa5-60e9-4fbf-8edb-edddb17cad2b"
  last_seen: "2023-10-15 10:34:00"
  success: true
  finished: true
  item_created_at: "2023-05-08 11:34:00"
  item_updated_at: "2023-05-09 20:34:00"
  item_deleted_at: "2023-05-09 20:34:00"
  active: true
