[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kronos_backtester"
version = "0.1.2"
authors = [
  { name="Quant Illinois", email="quant.illinois@gmail.com" },
]
description = "A backtesting framework for the trading strategies developed by Quant Illinois."
readme = "README.md"
requires-python = ">=3.7.1"
dependencies = [
  "pandas>=1.3.0", "plotly>= 5.18.0", "yfinance",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://https://github.com/quantillinois/kronos"
"Bug Tracker" = "https://https://github.com/quantillinois/kronos/issues"