[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pcr2echo"
version = "1.0.3"
authors = [
  { name="Elizabeth Gardner", email="egar18111@gmail.com" },
]
description = "Script to process PCR assembly sheet to an Echo CSV"
readme = "README.md"
requires-python = "== 3.10.5"

dependencies = [
  "pandas == 1.4.2",
  "openpyxl == 3.0.10",
  ]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"