[project]
name = "pypi_pdm_template"
version = "0.1.1"
description = "a template for build python package to upload pypi repository bu using pdm"
authors = [
    { name = "lgf4591", email = "lgf4591@outlook.com" },
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"

[project.license]
file = "LICENSE"

[project.urls]
Home = "https://github.com/lgf4591/pypi_pdm_template"
Changelog = "https://github.com/lgf4591/pypi_pdm_template/blob/main/CHANGELOG.md"
Docs = "https://github.com/lgf4591/pypi_pdm_template/blob/main/README.md#yapf"
Issues = "https://github.com/lgf4591/pypi_pdm_template/issues"

[tool.pdm]
source = [
    { url = "https://pypi.tuna.tsinghua.edu.cn/simple", name = "pypi" },
]

[tool.pdm.scripts.venv]
cmd = "pdm venv activate"

[tool.pdm.scripts._]
env_file = ".env"

[tool.pdm.scripts.start]
cmd = "python main.py"

[tool.pdm.scripts.lint]
cmd = "python -m flake8"

[tool.pdm.scripts.fix]
cmd = "yapf -ir main.py ./tests ./pypi_pdm_template"

[tool.pdm.scripts.test]
cmd = "python -m pytest"

[tool.pdm.scripts.all]
composite = [
    "lint pypi_pdm_template/ tests/",
    "test -v tests/",
]

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.4.3",
]
lint = [
    "flake8>=6.1.0",
    "mypy>=1.7.0",
    "pylint>=3.0.2",
]
format = [
    "isort>=5.12.0",
    "black>=23.11.0",
    "yapf>=0.40.2",
]
docs = [
    "mkdocs>=1.5.3",
]

[tool.distutils.bdist_wheel]
python_tag = "py3"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
