[project]
name = "classipypi"
dynamic = []
description = "Neurosymbolic PyPI package classifier selector."
authors = [
    { name = "Louis Maddox", email = "louismmx@gmail.com" },
]
keywords = [
    "pydantic",
    "pypi",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Topic :: Software Development :: Libraries",
    "Framework :: Pydantic",
    "Framework :: Pydantic :: 2",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "numpy>=1.26",
    "transformers",
    "pydantic>=2.4.2",
    "defopt",
    "trove-classifiers>=2023.10.18",
    "tomli-w>=1.0.0",
]
requires-python = ">=3.10,<3.13"
readme = "README.md"
version = "0.0.5"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/lmmx/classipypi"
Repository = "https://github.com/lmmx/classipypi.git"

[project.scripts]
classipypi = "classipypi.cli:run_cli"

[project.optional-dependencies]
outlines = [
    "torch>=2.1.0",
    "outlines>=0.0.9",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm.version]
source = "file"
path = "src/classipypi/__init__.py"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.4.0",
]

[tool.isort]
known_first_party = [
    "classipypi",
]
