[project]
name = "sec2time"
version = "0.1.0"
description = ""
authors = [
    { name = "TechieG", email = "35962141+gokulnath30@users.noreply.github.com" },
]
dependencies = [
    "pytest>=7.4.3",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool]
