[build-system]
requires = [
    "setuptools >= 65",
    "wheel >= 0.38",
]
build-backend = "setuptools.build_meta"

[project]
name = "kv_image_pipeline"
authors = [{name = "Justin Bui", email = "jmbui@klangverso.com"}]
version = "0.1.1"
requires-python = ">=3.8"
dependencies = [
    "kv_pdf_processor",
]