[project]
name = "py-pepe"
dynamic = []
description = "use python scripts in unix pipes"
readme = "README.md"
authors = [
    { name = "Denis Krumko", email = "dkrumko@gmail.ru" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
]
requires-python = ">=3.8"
version = "0.0.4"

[project.license]
text = "MIT"

[project.urls]
repository = "https://github.com/deniskrumko/py-pepe"

[project.optional-dependencies]
dev = [
    "flake8-pyproject",
    "flake8-commas",
    "flake8-isort !=5.0.1, !=5.0.2",
    "flake8-bugbear",
    "flake8-simplify",
    "flake8-debugger",
    "isort",
    "mypy",
    "pytest",
    "pytest-cov",
    "coverage[toml]",
]

[build-system]
requires = [
    "pdm-pep517>=1.0.0",
]
build-backend = "pdm.pep517.api"

[tool.pdm.version]
source = "scm"
write_to = "pepe/__version__.py"
write_template = "__version__ = '{}'"

[tool.flake8]
exclude = [
    ".git",
    ".idea",
    "__pycache__",
    "venv",
]
max-line-length = 100
ignore = [
    "C819",
    "W503",
    "SIM113",
    "SIM102",
    "SIM106",
    "SIM119",
    "SIM114",
    "SIM110",
    "SIM111",
    "SIM116",
]
per-file-ignores = [
    "*/__init__.py:F401",
]

[tool.pytest.ini_options]
addopts = "-s -l"

[tool.mypy]
exclude = [
    "tests",
    "fabfile\\.py",
]
namespace_packages = true
disable_error_code = "attr-defined"
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_return_any = true
warn_unreachable = true

[tool.isort]
line_length = 100
multi_line_output = 3
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
include_trailing_comma = true
force_grid_wrap = 2
combine_as_imports = true
use_parentheses = true

[tool.coverage.run]
relative_files = true
branch = true
source = [
    ".",
]
omit = [
    "*/tests/*",
    "./fabfile.py",
    "./pepe/__version__.py",
    "./setup.py",
]

[tool.coverage.report]
fail_under = 80
precision = 2
