[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "python-event-bus"
version = "1.2.0"
authors = [
  {name = "mxngo", email = ""}
]
description = "python-event-bus makes communication between python classes easier."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Topic :: Utilities",
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]